version: '3'
services:
  api:
    image: namespace/service-name:latest
    ports:
      - 8080:8080
    env_file: dev.env

  postgres:
    image: postgres:11.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development
      POSTGRES_DB: blog
